Molden Writer update
psi4/psi4 pull request #2229
Opened 2021-07-01 16:53 UTC by sgoodlett

## Description
Moved old Molden writer to Python, fixed normalization issue, and added test cases

## Todos

## Questions

## Checklist
- [Y ] Tests added for any new features
- [ Y] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

2021-07-01 16:58 UTC, JonathonMisiewicz commented
Happy to see this up!  Go ahead and mark this ready for review. You want to mark with a single "X" rather than "Y " or " Y" so you get pretty checkmarks.

This PR will close #1973. I was pretty heavily involved in this, so I _probably_ shouldn't review this one.

2021-07-01 17:09 UTC, JonathonMisiewicz commented on tests/PEDRA.OUT__19028
> +Point group: C1
This file shouldn't be here.

2021-07-01 17:09 UTC, JonathonMisiewicz commented on psi4/src/psi4/libmints/writer.h
> +class PSI_API MoldenWriter {
I think you misunderstood me earlier. Get rid of this "new" class and move the `PSI_DEPRECATED` warnings to the functions of the _existing_ `MoldenWriter` class. This is probably why the build is failing.

2021-07-01 20:24 UTC, jturney approved these changes

2021-07-01 20:32 UTC, loriab commented
Just checking that the extra precision added https://github.com/psi4/psi4/pull/1510/files didn't get lost.

2021-07-01 20:54 UTC, JonathonMisiewicz commented
> Just checking that the extra precision added https://github.com/psi4/psi4/pull/1510/files didn't get lost.

We studied numerical precision and couldn't justify going out to the **17** decimal places reported after #1510: the Python code couldn't reproduce the C++ code out that far. My memory is hazy, but I recall some errors that were normally in the 14th decimal place but could rarely reach to the 12th decimal place, which I suspected were related to the numerical precision of S^(-1/2). This made me want to cut back the number of decimal places to something less fragile.

I [checked in](https://github.com/psi4/psi4/issues/1973) about why we had 17 decimal places in the first place, and the person who made the change simply assumed that we had that many decimals of precision. In my judgment, we do not, and it was a mistake to ever report that many decimal places.

I _also_ checked that 10 decimal places was enough to keep #1486 fixed. (That was the issue that originally prompted the increased precision in our Molden files.) While the 4 decimal places of the pre-#1486 era had the bug, the 10 decimal places of this PR did not.

While we could _maybe_ go out to 11 or 12 decimal places, trying to get 17 decimal places of precision would require an analysis of round-off error in every line of the SCF code. This seems far beyond the scope of the PR.

2021-07-02 13:18 UTC, jturney requested changes

2021-07-02 13:18 UTC, jturney commented on psi4/src/psi4/libmints/writer.cc
> +MoldenWriter::MoldenWriter(std::shared_ptr<Wavefunction> wavefunction) : wavefunction_(wavefunction) {
Why did you duplicate the function from line 55. The compiler is reporting an error.  This should have come up on your local compile. One of them must be deleted.

2021-07-07 02:23 UTC, JonathonMisiewicz commented
We might as well fix #2238 while we're at it. The problematic line of code is [right here](https://github.com/psi4/psi4/pull/2229/files#diff-21e554583cfa696eeabb7d40e85e87689e1bd9f72ff88e593fdac893c6b61ac9R356).

2021-07-07 21:12 UTC, JonathonMisiewicz approved these changes
That's much better, thank you. I'll approve this in the interests of expediting 1.4. If anybody thinks we need three _independent_ reviewers, just say so.

2021-07-08 16:44 UTC, jturney approved these changes

2021-07-19 14:43 UTC, loriab approved these changes

2021-07-19 14:53 UTC, andysim approved these changes
Excellent work!  This is exactly the kind of thing the belongs py-side.  Kudos for the extensive tests.

2021-07-19 14:58 UTC, JonathonMisiewicz commented on psi4/driver/p4util/writer.py
> +        MO_Db.print_out()
Good catch. This is probably a debugging statement that survived.

2021-07-19 17:26 UTC, merged