Better Error Message for Issue #2890
psi4/psi4 pull request #2906
Opened 2023-03-23 17:35 UTC by davpoolechem

## Description
This PR provides a more useful error message when the issue described in https://github.com/psi4/psi4/issues/2890 is encountered. In short, the COSX K build method breaks with certain grid configurations - specifically, grid configurations which result in negative grid weights. How to best handle that issue - removing such grid configurations from Psi4 entirely, handling negative grid weights differently within COSX itself - is still under discussion, and this PR is _not_ meant to be a final fix to the aforementioned issue.

Rather, this PR is meant to provide a more informative error message in the case that an end user _does_ encounter this error. Currently, when this error is encountered, it shows up as either a DGESV error (if the initial COSX grid has negative weights) or an ADIIS minimization error (if the final COSX grid has negative weights). These error outputs don't help the end user figure out what is wrong at all. So, what this PR does, is add sanity checks to ensure that the COSX grids don't have negative weights, and throw an exception if they do. The sanity check exceptions explain to the user what the error is and how they can fix it (i.e., changing the grid pruning scheme and/or number of spherical points).

Again, I want to emphasize that this is _not_ intended to be a full fix to https://github.com/psi4/psi4/issues/2890. Rather, it is an intermediate step that is designed to better help end users avoid the problem if they run into it themselves.

## User API & Changelog headlines
N/A

## Dev notes & details
- [X] Add sanity checks to COSX to ensure that neither of the COSX grids have negative grid weights. An exception is thrown if either of the grids do.

## Questions
- [ ] Probably better discussed on https://github.com/psi4/psi4/issues/2890, but how do we want to officially solve this problem? There has been some discussion on simply removing grid configurations which lead to negative weights, as well as discussions on reformulating the X matrix (the matrix central to the observed error) to be able to handle positive grid weights. 

## Checklist
- [X] Tests added for any new features
- [X] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [X] Ready for review
- [ ] Ready for merge

2023-03-24 19:51 UTC, loriab approved these changes

2023-04-05 18:36 UTC, JonathonMisiewicz commented
Please update the error message to say that the grid is unusable with COSX, rather than "better fix" incoming.

2023-04-05 18:36 UTC, JonathonMisiewicz requested changes
See above.

2023-04-05 18:48 UTC, loriab commented
Maybe language like "The definition of the current grid includes negative weights. As these are not suitable for the COSX implementation, please choose another grid through ...".

2023-04-05 19:01 UTC, davpoolechem commented
> Please update the error message to say that the grid is unusable with COSX, rather than "better fix" incoming.

> See above.

> Maybe language like "The definition of the current grid includes negative weights. As these are not suitable for the COSX implementation, please choose another grid through ...".

Done and done! Wording changed to match these suggestions.

Also, for those not at the Psi4 dev meeting today, it was agreed upon that this PR would indeed be the final fix to the COSX grid issue.

2023-04-05 19:20 UTC, JonathonMisiewicz approved these changes
I'd mark `w` as `const auto` for good measure, but I'm fine with the PR being merged as-is.

2023-04-05 19:24 UTC, davpoolechem commented
> I'd mark `w` as `const auto` for good measure, but I'm fine with the PR being merged as-is.

Yeah, I can do that! Give a quick sec, and we can probably merge after that.

2023-04-05 19:31 UTC, davpoolechem commented
Done! We should be good on this front.

2023-04-14 21:10 UTC, loriab commented
@mfherbst , there's a couple of the ddx tests failing now https://github.com/psi4/psi4/actions/runs/4703123664/jobs/8341938828?pr=2906#step:23:739, and I suspect it's because of the v0.4.1 released yesterday since it was working fine with v0.3.0 after your #2918 . Does this sound right? If so, we can pin to v0.3 unless you have a PR in the works.

2023-04-19 20:13 UTC, merged